# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-21 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12, verbose_name='标题')),
                ('icon', models.CharField(max_length=12, verbose_name='图标')),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=32, verbose_name='URL')),
                ('title', models.CharField(max_length=12, verbose_name='名称')),
                ('name', models.CharField(max_length=12, verbose_name='别名')),
                ('memu', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Memu', unique=True, verbose_name='管理菜单')),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Permissions', unique=True, verbose_name='父菜单')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='名称')),
                ('permissions', models.ManyToManyField(to='rbac.Permissions', verbose_name='关联权限')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('roles', models.ManyToManyField(to='rbac.Role', verbose_name='关联角色')),
            ],
        ),
    ]
