# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-21 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='memu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Memu', verbose_name='管理菜单'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='name',
            field=models.CharField(max_length=12, unique=True, verbose_name='别名'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Permissions', verbose_name='父菜单'),
        ),
    ]
